"""Runtime source of truth for the wigolo REST tool surface.

Each entry describes one tool endpoint: its HTTP path, required params,
the full ordered param list (mirrored EXACTLY by the client method
signatures), the response keys the server may emit, and the default
per-tool timeout in seconds.

The timeouts mirror the server's UNSCALED per-route deadlines. If the
server runs with ``WIGOLO_SERVE_TIMEOUT_SCALE`` set, the effective server
deadline scales but these client defaults do not — override per call or
per client when the server is scaled.
"""

from __future__ import annotations

from typing import TypedDict


class ToolSpec(TypedDict):
    path: str
    required: list[str]
    params: list[str]
    responseKeys: list[str]
    default_timeout_s: int


MANIFEST: dict[str, ToolSpec] = {
    "search": {
        "path": "/v1/search",
        "required": ["query"],
        "params": [
            "query",
            "max_results",
            "max_fetches",
            "include_content",
            "content_max_chars",
            "max_content_chars",
            "max_total_chars",
            "time_range",
            "exact_match",
            "search_engines",
            "language",
            "country",
            "include_domains",
            "exclude_domains",
            "from_date",
            "to_date",
            "category",
            "format",
            "max_highlights",
            "force_refresh",
            "include_favicon",
            "include_images",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
            "mode",
            "search_depth",
            "agent_context",
        ],
        "responseKeys": [
            "results",
            "query",
            "engines_used",
            "total_time_ms",
            "response_time_ms",
            "evidence",
            "citations",
            "highlights",
            "answer",
            "warning",
            "error",
        ],
        "default_timeout_s": 75,
    },
    "fetch": {
        "path": "/v1/fetch",
        "required": ["url"],
        "params": [
            "url",
            "render_js",
            "use_auth",
            "max_chars",
            "max_content_chars",
            "section",
            "section_index",
            "screenshot",
            "headers",
            "force_refresh",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
            "actions",
            "mode",
        ],
        "responseKeys": [
            "url",
            "title",
            "markdown",
            "metadata",
            "links",
            "images",
            "cached",
            "fetch_method",
            "http_status",
            "site_data",
            "evidence",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 135,
    },
    "crawl": {
        "path": "/v1/crawl",
        "required": ["url"],
        "params": [
            "url",
            "max_depth",
            "max_pages",
            "strategy",
            "include_patterns",
            "exclude_patterns",
            "use_auth",
            "extract_links",
            "max_total_chars",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
        ],
        "responseKeys": [
            "pages",
            "total_found",
            "crawled",
            "links",
            "urls",
            "sitemap_found",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 315,
    },
    "cache": {
        "path": "/v1/cache",
        "required": [],
        "params": [
            "query",
            "url_pattern",
            "since",
            "clear",
            "stats",
            "check_changes",
            "mode",
            "limit",
            "max_tokens_out",
        ],
        "responseKeys": [
            "results",
            "stats",
            "cleared",
            "changes",
            "error",
        ],
        "default_timeout_s": 75,
    },
    "extract": {
        "path": "/v1/extract",
        "required": [],
        "params": [
            "url",
            "html",
            "mode",
            "css_selector",
            "multiple",
            "schema",
            "named_schema",
            "max_tokens_out",
        ],
        "responseKeys": [
            "data",
            "source_url",
            "mode",
            "warnings",
            "truncated",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 135,
    },
    "find_similar": {
        "path": "/v1/find_similar",
        "required": [],
        "params": [
            "url",
            "concept",
            "max_results",
            "include_domains",
            "exclude_domains",
            "include_cache",
            "include_web",
            "mode",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
            "threshold",
            "include_ranking_debug",
        ],
        "responseKeys": [
            "results",
            "method",
            "cache_hits",
            "search_hits",
            "embedding_available",
            "cold_start",
            "total_time_ms",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 75,
    },
    "research": {
        "path": "/v1/research",
        "required": ["question"],
        "params": [
            "question",
            "depth",
            "max_sources",
            "include_domains",
            "exclude_domains",
            "schema",
            "stream",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
        ],
        "responseKeys": [
            "report",
            "citations",
            "sources",
            "sub_queries",
            "depth",
            "total_time_ms",
            "sampling_supported",
            "brief",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 315,
    },
    "agent": {
        "path": "/v1/agent",
        "required": ["prompt"],
        "params": [
            "prompt",
            "urls",
            "schema",
            "max_pages",
            "max_time_ms",
            "stream",
            "max_tokens_out",
            "include_full_markdown",
            "citation_format",
        ],
        "responseKeys": [
            "result",
            "sources",
            "pages_fetched",
            "steps",
            "total_time_ms",
            "sampling_supported",
            "warning",
            "response_time_ms",
            "error",
        ],
        "default_timeout_s": 315,
    },
    "diff": {
        "path": "/v1/diff",
        "required": [],
        "params": [
            "old",
            "new",
            "output",
            "granularity",
        ],
        "responseKeys": [
            "changed",
            "unified_diff",
            "hunks",
            "summary",
            "truncated",
        ],
        "default_timeout_s": 75,
    },
    "watch": {
        "path": "/v1/watch",
        "required": ["action"],
        "params": [
            "action",
            "url",
            "urls",
            "interval_seconds",
            "selector",
            "notification",
            "job_id",
        ],
        "responseKeys": [
            "job",
            "jobs",
            "changes_since_last",
            "notice",
        ],
        "default_timeout_s": 135,
    },
}

TOOL_NAMES: tuple[str, ...] = tuple(MANIFEST.keys())
